#!/bin/sh

i=1
for svg in build/*svg; do
    echo "${svg}"
    pdf="${svg%.*}.pdf"
    png="${svg%.*}.png"

    inkscape "${svg}" \
             --batch-process --export-type=pdf --export-background=white \
             --export-filename="${pdf}"

    inkscape "${svg}" \
             --batch-process --export-type=png --export-background=white \
             --export-filename="${png}"

    # build the json
    echo "{
  \"name\": \"draw-something (txes) #$(printf '%02d' ${i})\",
  \"description\": \"A token representing a drawing of the transaction that created that token. The token hash is read as the co-ordinates of the inner guide form, and a rule-based AI system called draw-something creates a freehand-style drawing around it.\",
  \"image\": \"${png##*/}\"
}" \
         > "build/${i}"
    i=$(( i + 1 ))
done
