#!/bin/sh
#|-*- mode:lisp -*-|#
#|
exec ros --load-system draw-something -- $0 "$@"
|#

(defconstant hashes-filename "tx-hashes")

(defconstant hashes
  (with-open-file (stream hashes-filename)
    (loop for line = (read-line stream nil)
          while line
          collect line))
  "A list of the 64-char hexadecimal string hashes to turn into skeletons")

(defconstant edition-size (length hashes)
  "How many drawings to produce.")

#|
(defconstant ds (+ (ash (char-code #\d) 24)
(ash (char-code #\s) 16))
"The string 'ds' in the upper 16 bits of a 32-bit int")

(defun make-initvec (str)
"Convert a string of <= 32 chars to a Solidity-style bytes value
as an array of 32 unsigned bytes."
(let ((string-len (length str)))
(assert (<= string-len 32))
(coerce
(loop for i from 0 to 31
collect (if (< i string-len)
(char-code (char str i))
0))
'(array (unsigned-byte 32) (*)))))
|#

;; Units are mm

(defparameter *pen-params*
  (make-instance 'draw-something::<pen-parameters>
                 :move-step          0.35  ;; 1.3px ;;1.0
                 :distance           1.4   ;; 5.2 px
                 :distance-tolerance 0.2   ;; 0.7 px
                 :turn-step          0.01  ;;0.1
                 :drift-probability  0.0
                 :drift-range        0.0)) ;;0.1

;; 17 x 14" in mm = 432 x 356 mm
;; Axidraw V3A3 travel in mm = 430 x 297 mm
;; We need a square that fits, so it has to be 297 x 297 mm
;; This amounts to a 297mm column, with a 297mm square in the vertical center
;; of the page height (not the plotter y travel distance).


(defparameter +page-size+ '(297 . 356))
(defparameter +skeleton-inset+ (* 2
                                  (draw-something::pen-distance *pen-params*)))
;; https://github.com/evil-mad/axidraw/blob/master/inkscape%20driver/axidraw_conf.py#L145
(defparameter +drawing-size+ (cons (- 297 +skeleton-inset+)
                                   (- 297 +skeleton-inset+)))
(defparameter +drawing-x+ (/ (- (car +page-size+) (car +drawing-size+)) 2.0))
(defparameter +drawing-y+ (/ (- (cdr +page-size+) (cdr +drawing-size+)) 2.0))

(defun draw-something (pathspec hash randseed)
  "Make the drawing data structures and create the image."
  (draw-something::advisory-message "Starting draw-something.~%")
  (draw-something::random-init randseed)
  (let* ((drawing-bounds (make-instance 'draw-something::<rectangle>
                                        :x +drawing-x+
                                        :y +drawing-y+
                                        :width (car +drawing-size+)
                                        :height (cdr +drawing-size+)))
         (points (draw-something::hash-to-points
                  hash
                  (draw-something::x drawing-bounds)
                  (draw-something::y drawing-bounds)
                  (draw-something::width drawing-bounds)
                  (draw-something::height drawing-bounds)))
         (form (draw-something::make-form-from-points points)))
    (draw-something::draw-form form *pen-params*)
    (draw-something::advisory-message "Finished drawing.~%")
    (let ((filepath
           (draw-something::write-svg-form
            form
            (make-instance draw-something::'<rectangle>
                           :x 0
                           :y 0
                           :width (car +page-size+)
                           :height (cdr +page-size+))
            pathspec)))
      (draw-something::advisory-message "Finished draw-something.~%")
      filepath)))

(defun main ()
  (let ((edition-number 1))
    (dolist (hash hashes)
      (draw-something
       (format nil "draw-something-edition-~2,'0d.svg" edition-number)
       hash
       edition-number)
      (incf edition-number))
    "Done."))
